### PR TITLE
Add brief documentation of methods and options.

### PR DESCRIPTION
**Pull request by donmccurdy**

### CODE REVIEW

**Comment by cyrilchapon** [comment]
I think the input of `load(`points`)` is an array of `Feature<Point>` more that and array of `Point`

**Comment by donmccurdy** [comment]
@cyrilchapon right you are, thanks!

**Comment by mourner** [comment]
Thanks for the PR and sorry for a late response! This looks good except for `radius` option, which is not only for tiles. It affects how clustering works.

**Comment by donmccurdy** [comment]
Updated — is the `radius` option description good other than that?

**Comment by mourner** [comment]
I would add a note to `extent` indicating that `radius` is relative to it (https://github.com/mapbox/supercluster/blob/master/index.js#L21)

Those options are not super-well-descriptive, but I'll think about a better explanation for future.

**Comment by donmccurdy** [comment]
Sounds good; done.

**Pull request merged**
