### PR TITLE
Support for custom metrics on each cluster

### PR DESCRIPTION
**Pull request by georgeke**
Currently, the only metric we have for each cluster is the number of points in each cluster. 

I ran into this "limitation" when wanting to display a number on each cluster which was an aggregation of a custom property on each of my points. **For example, each point may have a `population` property, and I want each cluster to show the total population.**

This PR allows points passed in to have an additional property specified by `metricKey` and a custom reducer function specified by `metricReducer`.

Now, one can compute metrics on clusters that are based on other dimensions (like `population`) and compute things like averages, min, max, etc.

### CODE REVIEW

**Comment by mourner** [comment]
Nice, thanks for the PR! I wonder whether we need to supply metric _in addition_ to `point_count`, rather than just implementing `point_count` in terms of those options?

**Comment by georgeke** [comment]
That could be possible if we define having metricKey=undefined mean we return metric: numPoints. I feel that it might be a stretch since metricKey doesn't have much to do with `point_count`.

There are a few advantages I see with keeping `point_count`
  1. In my mind, a `point_count` is a standard property that all clusters should have, whereas `metric` is more of a computed property that may not even be a number (could be a list, string, etc. depending on what you're doing). So keeping these separate could make more sense to the user.
  2. backwards compatibility. The same key is still there so people's code won't break. 

I'm leaning towards keeping it separate, what are your thoughts?

**Comment by georgeke** [comment]
@mourner Any thoughts/updates on this? If it's not high priority maybe I can close the PR for now.

**Comment by mourner** [comment]
@georgeke it's not high priority but let's keep it open — I'll get to it.

**Comment by georgeke** [comment]
@mourner thanks!

**Comment by ben657** [comment]
As a stepping stone to something like this, would it make sense to be able to get the points in a cluster, given its bounding box? I get this is doable just using the points and some other method to work out what's in the bounding box, but since they're already indexed here it might make sense to add.

This way we could get the points to go along with a cluster, then just iterate over them to calculate whatever needs calculating and add that to the clusters properties.

**Comment by redbmk** [comment]
@ben657 In theory if you've already aggregated a cluster, you shouldn't need to go through each of those points again. Say you have a cluster with 1000 points, and you already have the sum of some property for all those points, then you should only need to add the new point to the cluster instead of having to go through all of them again.

**Comment by aparshin** [comment]
Useful feature for general purpose clustering library!

@mourner It's a pity this PR is still not merged. Can I help somehow?

**Comment by redbmk** [comment]
@aparshin There's also some discussion about this in mapbox/mapbox-gl#26. I have some similar code that will help integrate into mapbox and be a little more flexible on the supercluster side of things, but could use some help writing tests and benchmarks, possibly making it faster, and I think the spec needs some work.

**Comment by johnlaur** [comment]
I have been following the many forks implementing this feature or something similar for the past month or so, and I really like the implementation from @redbmk because it allows for at arbitrary algorithms in the clustering engine. I understand the restrictions preventing such things in the style definition, but I would prefer not to completely close the door to somehow exposing this to in the end user API or through some kind of plugin scheme in the future. In either case it's extremely useful to have for preprocessing clusters on the server-side.

**Comment by lamuertepeluda** [comment]
Hi, I solved the conflicts of https://github.com/redbmk/supercluster with the current branch

See https://github.com/redbmk/supercluster/pull/2

I also enhanced the demo showing categories percentages on the tooltips on the map clusters.

If you could integrate I would be very happy (I'd need this feature so badly also in mapbox-gl)

**Comment by mourner** [comment]
@lamuertepeluda yes, I work on this currently — thanks for the help!

**Comment by lamuertepeluda** [comment]
@mourner I also updated the demo of the supercluster in order to show how pass a custom aggregator function defined into the main thread to the background worker via Blob.

See https://github.com/redbmk/supercluster/pull/3 and https://github.com/mapbox/mapbox-gl-js/issues/2412#issuecomment-276036081

**Comment by mourner** [comment]
Closing in favor of #36.

**Pull request closed without merging**
